### ISSUE TITLE
Rename w3?

### ISSUE THREAD

**Issue by dOrgJelli** [twilson63/w3#5]
Hello, I'm wondering if you would be willing to rename this project, and unpublishing from npmjs.com. I'd like to use the name `w3` for the CLI of a project I'm currently building.

It looks like your package meets all the requirements for unpublishing: https://www.npmjs.com/policies/unpublish

Please feel free to email to discuss details further, as I do realize this is an inconvenience on your end: jelli@dorg.tech

Kind regards,
Jordan

**Comment by twilson63** [comment]
No, I love using w3 and so do others

Thanks

Tom
